/**
 * Builds the help-article index the AI assistant searches (title, summary,
 * headings, path, platform) from src/content/help/**.mdx.
 *
 * The API is a separate package and must not read the web app's source at
 * runtime, so the index is generated into packages/shared/src/help-index.generated.ts
 * (committed). `pnpm --filter @fintranzact/web gen:help-index` rewrites it, the
 * web build runs it first, and a web test fails when the committed file differs
 * from what this builds, so it cannot go stale unnoticed.
 */
import { readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

export type GeneratedHelpEntry = {
  slug: string;
  path: string;
  title: string;
  summary: string;
  headings: string[];
  /** The first numbered steps of the article (desktop steps first), so a "how do I" answer has something to summarise. */
  steps: string[];
  platform: "web" | "web_and_mobile" | "any";
};

const HERE = typeof import.meta.dirname === "string" ? import.meta.dirname : path.dirname(fileURLToPath(import.meta.url));

export const HELP_CONTENT_ROOT = path.resolve(HERE, "../src/content/help");
export const HELP_INDEX_OUTPUT = path.resolve(HERE, "../../../packages/shared/src/help-index.generated.ts");

const MAX_SUMMARY = 220;
const MAX_HEADINGS = 14;
const MAX_HEADING_CHARS = 80;
const MAX_STEPS = 8;
const MAX_STEP_CHARS = 140;

function walk(dir: string): string[] {
  return readdirSync(dir)
    .sort()
    .flatMap((entry) => {
      const full = path.join(dir, entry);
      return statSync(full).isDirectory() ? walk(full) : entry.endsWith(".mdx") ? [full] : [];
    });
}

function slugOf(root: string, file: string): string {
  return path
    .relative(root, file)
    .split(path.sep)
    .join("/")
    .replace(/\.mdx$/, "")
    .replace(/(^|\/)index$/, "");
}

/** Plain text of a heading or sentence: markdown links, emphasis, code ticks and braces removed. */
function plain(text: string): string {
  return text
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/[*_`]/g, "")
    .replace(/[{}<>]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function clip(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max - 1).trimEnd()}…` : text;
}

export function buildHelpIndex(root: string = HELP_CONTENT_ROOT): GeneratedHelpEntry[] {
  const entries = walk(root).map((file): GeneratedHelpEntry => {
    const raw = readFileSync(file, "utf-8").replace(/\r\n/g, "\n");
    const match = /^---\n([\s\S]*?)\n---\n?/.exec(raw);
    const fm = match ? ((parseYaml(match[1]!) as Record<string, unknown>) ?? {}) : {};
    const body = (match ? raw.slice(match[0].length) : raw).replace(/```[\s\S]*?```/g, "");
    const slug = slugOf(root, file);
    const headings: string[] = [];
    for (const line of body.split("\n")) {
      const h = /^#{2,3}\s+(.+?)\s*#*$/.exec(line);
      if (!h) continue;
      const text = clip(plain(h[1]!), MAX_HEADING_CHARS);
      if (text && !headings.includes(text)) headings.push(text);
      if (headings.length >= MAX_HEADINGS) break;
    }
    const desktop = body.includes("ForDesktop");
    const mobile = body.includes("ForMobile");
    // Steps: numbered list items, taken from the desktop part when the article has a mobile part too.
    const mobileAt = body.indexOf("<ForMobile");
    const stepSource = desktop && mobile && mobileAt > 0 ? body.slice(0, mobileAt) : body;
    const steps: string[] = [];
    for (const line of stepSource.split("\n")) {
      const st = /^\s{0,3}\d+\.\s+(.+)$/.exec(line);
      if (!st) continue;
      const text = clip(plain(st[1]!), MAX_STEP_CHARS);
      if (text) steps.push(text);
      if (steps.length >= MAX_STEPS) break;
    }
    return {
      slug,
      path: slug ? `/help/${slug}` : "/help",
      title: clip(plain(String(fm.title ?? slug)), 100),
      summary: clip(plain(String(fm.description ?? "")), MAX_SUMMARY),
      headings,
      steps,
      platform: desktop && mobile ? "web_and_mobile" : desktop ? "web" : "any",
    };
  });
  return entries.sort((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0));
}

/** The exact text of packages/shared/src/help-index.generated.ts. */
export function renderHelpIndexModule(entries: GeneratedHelpEntry[]): string {
  return [
    "// GENERATED by apps/web/scripts/gen-help-index.ts from apps/web/src/content/help. Do not edit by hand:",
    "// run `pnpm --filter @fintranzact/web gen:help-index`. A web test fails when this file is out of date.",
    'import type { HelpIndexEntry } from "./ai-help.js";',
    "",
    "export const HELP_INDEX: readonly HelpIndexEntry[] = [",
    ...entries.map((e) => `  ${JSON.stringify(e)},`),
    "];",
    "",
  ].join("\n");
}
