/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoreOrdersRouteImport } from './routes/store-orders'
import { Route as StockTransfersRouteImport } from './routes/stock-transfers'
import { Route as StockAdjustmentsRouteImport } from './routes/stock-adjustments'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesReturnsRouteImport } from './routes/sales-returns'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProformaInvoicesRouteImport } from './routes/proforma-invoices'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PhysicalStockRouteImport } from './routes/physical-stock'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalEntriesRouteImport } from './routes/journal-entries'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as ItcRouteImport } from './routes/itc'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as Gstr2bRouteImport } from './routes/gstr2b'
import { Route as GstRouteImport } from './routes/gst'
import { Route as GoodsReceiptNotesRouteImport } from './routes/goods-receipt-notes'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EwayBillsRouteImport } from './routes/eway-bills'
import { Route as EInvoicingRouteImport } from './routes/e-invoicing'
import { Route as DeliveryChallansRouteImport } from './routes/delivery-challans'
import { Route as CreditNotesRouteImport } from './routes/credit-notes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CashAndBankRouteImport } from './routes/cash-and-bank'
import { Route as BankReconciliationRouteImport } from './routes/bank-reconciliation'
import { Route as AutomatedInvoicesRouteImport } from './routes/automated-invoices'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ITokenRouteImport } from './routes/i/$token'
import { Route as BusinessCreateRouteImport } from './routes/business/create'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthPlanSelectionRouteImport } from './routes/auth/plan-selection'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/store-orders',
  path: '/store-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTransfersRoute = StockTransfersRouteImport.update({
  id: '/stock-transfers',
  path: '/stock-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAdjustmentsRoute = StockAdjustmentsRouteImport.update({
  id: '/stock-adjustments',
  path: '/stock-adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReturnsRoute = SalesReturnsRouteImport.update({
  id: '/sales-returns',
  path: '/sales-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaInvoicesRoute = ProformaInvoicesRouteImport.update({
  id: '/proforma-invoices',
  path: '/proforma-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalStockRoute = PhysicalStockRouteImport.update({
  id: '/physical-stock',
  path: '/physical-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntriesRoute = JournalEntriesRouteImport.update({
  id: '/journal-entries',
  path: '/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ItcRoute = ItcRouteImport.update({
  id: '/itc',
  path: '/itc',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const Gstr2bRoute = Gstr2bRouteImport.update({
  id: '/gstr2b',
  path: '/gstr2b',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRoute = GstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsReceiptNotesRoute = GoodsReceiptNotesRouteImport.update({
  id: '/goods-receipt-notes',
  path: '/goods-receipt-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EwayBillsRoute = EwayBillsRouteImport.update({
  id: '/eway-bills',
  path: '/eway-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const EInvoicingRoute = EInvoicingRouteImport.update({
  id: '/e-invoicing',
  path: '/e-invoicing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryChallansRoute = DeliveryChallansRouteImport.update({
  id: '/delivery-challans',
  path: '/delivery-challans',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditNotesRoute = CreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CashAndBankRoute = CashAndBankRouteImport.update({
  id: '/cash-and-bank',
  path: '/cash-and-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const BankReconciliationRoute = BankReconciliationRouteImport.update({
  id: '/bank-reconciliation',
  path: '/bank-reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatedInvoicesRoute = AutomatedInvoicesRouteImport.update({
  id: '/automated-invoices',
  path: '/automated-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCreateRoute = BusinessCreateRouteImport.update({
  id: '/business/create',
  path: '/business/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPlanSelectionRoute = AuthPlanSelectionRouteImport.update({
  id: '/auth/plan-selection',
  path: '/auth/plan-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automated-invoices': typeof AutomatedInvoicesRoute
  '/bank-reconciliation': typeof BankReconciliationRoute
  '/cash-and-bank': typeof CashAndBankRoute
  '/contact': typeof ContactRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/e-invoicing': typeof EInvoicingRoute
  '/eway-bills': typeof EwayBillsRoute
  '/expenses': typeof ExpensesRoute
  '/features': typeof FeaturesRoute
  '/goods-receipt-notes': typeof GoodsReceiptNotesRoute
  '/gst': typeof GstRoute
  '/gstr2b': typeof Gstr2bRoute
  '/invoices': typeof InvoicesRoute
  '/itc': typeof ItcRoute
  '/items': typeof ItemsRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parties': typeof PartiesRoute
  '/partners': typeof PartnersRoute
  '/payments': typeof PaymentsRoute
  '/physical-stock': typeof PhysicalStockRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proforma-invoices': typeof ProformaInvoicesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/stock-transfers': typeof StockTransfersRoute
  '/store-orders': typeof StoreOrdersRoute
  '/terms': typeof TermsRoute
  '/warehouses': typeof WarehousesRoute
  '/widgets': typeof WidgetsRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/plan-selection': typeof AuthPlanSelectionRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/business/create': typeof BusinessCreateRoute
  '/i/$token': typeof ITokenRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automated-invoices': typeof AutomatedInvoicesRoute
  '/bank-reconciliation': typeof BankReconciliationRoute
  '/cash-and-bank': typeof CashAndBankRoute
  '/contact': typeof ContactRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/e-invoicing': typeof EInvoicingRoute
  '/eway-bills': typeof EwayBillsRoute
  '/expenses': typeof ExpensesRoute
  '/features': typeof FeaturesRoute
  '/goods-receipt-notes': typeof GoodsReceiptNotesRoute
  '/gst': typeof GstRoute
  '/gstr2b': typeof Gstr2bRoute
  '/invoices': typeof InvoicesRoute
  '/itc': typeof ItcRoute
  '/items': typeof ItemsRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parties': typeof PartiesRoute
  '/partners': typeof PartnersRoute
  '/payments': typeof PaymentsRoute
  '/physical-stock': typeof PhysicalStockRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proforma-invoices': typeof ProformaInvoicesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/stock-transfers': typeof StockTransfersRoute
  '/store-orders': typeof StoreOrdersRoute
  '/terms': typeof TermsRoute
  '/warehouses': typeof WarehousesRoute
  '/widgets': typeof WidgetsRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/plan-selection': typeof AuthPlanSelectionRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/business/create': typeof BusinessCreateRoute
  '/i/$token': typeof ITokenRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automated-invoices': typeof AutomatedInvoicesRoute
  '/bank-reconciliation': typeof BankReconciliationRoute
  '/cash-and-bank': typeof CashAndBankRoute
  '/contact': typeof ContactRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/e-invoicing': typeof EInvoicingRoute
  '/eway-bills': typeof EwayBillsRoute
  '/expenses': typeof ExpensesRoute
  '/features': typeof FeaturesRoute
  '/goods-receipt-notes': typeof GoodsReceiptNotesRoute
  '/gst': typeof GstRoute
  '/gstr2b': typeof Gstr2bRoute
  '/invoices': typeof InvoicesRoute
  '/itc': typeof ItcRoute
  '/items': typeof ItemsRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parties': typeof PartiesRoute
  '/partners': typeof PartnersRoute
  '/payments': typeof PaymentsRoute
  '/physical-stock': typeof PhysicalStockRoute
  '/pos': typeof PosRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/proforma-invoices': typeof ProformaInvoicesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/stock-transfers': typeof StockTransfersRoute
  '/store-orders': typeof StoreOrdersRoute
  '/terms': typeof TermsRoute
  '/warehouses': typeof WarehousesRoute
  '/widgets': typeof WidgetsRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/plan-selection': typeof AuthPlanSelectionRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/business/create': typeof BusinessCreateRoute
  '/i/$token': typeof ITokenRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/automated-invoices'
    | '/bank-reconciliation'
    | '/cash-and-bank'
    | '/contact'
    | '/credit-notes'
    | '/delivery-challans'
    | '/e-invoicing'
    | '/eway-bills'
    | '/expenses'
    | '/features'
    | '/goods-receipt-notes'
    | '/gst'
    | '/gstr2b'
    | '/invoices'
    | '/itc'
    | '/items'
    | '/journal-entries'
    | '/login'
    | '/onboarding'
    | '/parties'
    | '/partners'
    | '/payments'
    | '/physical-stock'
    | '/pos'
    | '/pricing'
    | '/privacy'
    | '/proforma-invoices'
    | '/purchase-orders'
    | '/quotations'
    | '/refund-policy'
    | '/register'
    | '/reports'
    | '/sales-orders'
    | '/sales-returns'
    | '/settings'
    | '/shipments'
    | '/stock-adjustments'
    | '/stock-transfers'
    | '/store-orders'
    | '/terms'
    | '/warehouses'
    | '/widgets'
    | '/auth/complete-profile'
    | '/auth/plan-selection'
    | '/auth/verify'
    | '/business/create'
    | '/i/$token'
    | '/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/automated-invoices'
    | '/bank-reconciliation'
    | '/cash-and-bank'
    | '/contact'
    | '/credit-notes'
    | '/delivery-challans'
    | '/e-invoicing'
    | '/eway-bills'
    | '/expenses'
    | '/features'
    | '/goods-receipt-notes'
    | '/gst'
    | '/gstr2b'
    | '/invoices'
    | '/itc'
    | '/items'
    | '/journal-entries'
    | '/login'
    | '/onboarding'
    | '/parties'
    | '/partners'
    | '/payments'
    | '/physical-stock'
    | '/pos'
    | '/pricing'
    | '/privacy'
    | '/proforma-invoices'
    | '/purchase-orders'
    | '/quotations'
    | '/refund-policy'
    | '/register'
    | '/reports'
    | '/sales-orders'
    | '/sales-returns'
    | '/settings'
    | '/shipments'
    | '/stock-adjustments'
    | '/stock-transfers'
    | '/store-orders'
    | '/terms'
    | '/warehouses'
    | '/widgets'
    | '/auth/complete-profile'
    | '/auth/plan-selection'
    | '/auth/verify'
    | '/business/create'
    | '/i/$token'
    | '/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/automated-invoices'
    | '/bank-reconciliation'
    | '/cash-and-bank'
    | '/contact'
    | '/credit-notes'
    | '/delivery-challans'
    | '/e-invoicing'
    | '/eway-bills'
    | '/expenses'
    | '/features'
    | '/goods-receipt-notes'
    | '/gst'
    | '/gstr2b'
    | '/invoices'
    | '/itc'
    | '/items'
    | '/journal-entries'
    | '/login'
    | '/onboarding'
    | '/parties'
    | '/partners'
    | '/payments'
    | '/physical-stock'
    | '/pos'
    | '/pricing'
    | '/privacy'
    | '/proforma-invoices'
    | '/purchase-orders'
    | '/quotations'
    | '/refund-policy'
    | '/register'
    | '/reports'
    | '/sales-orders'
    | '/sales-returns'
    | '/settings'
    | '/shipments'
    | '/stock-adjustments'
    | '/stock-transfers'
    | '/store-orders'
    | '/terms'
    | '/warehouses'
    | '/widgets'
    | '/auth/complete-profile'
    | '/auth/plan-selection'
    | '/auth/verify'
    | '/business/create'
    | '/i/$token'
    | '/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutomatedInvoicesRoute: typeof AutomatedInvoicesRoute
  BankReconciliationRoute: typeof BankReconciliationRoute
  CashAndBankRoute: typeof CashAndBankRoute
  ContactRoute: typeof ContactRoute
  CreditNotesRoute: typeof CreditNotesRoute
  DeliveryChallansRoute: typeof DeliveryChallansRoute
  EInvoicingRoute: typeof EInvoicingRoute
  EwayBillsRoute: typeof EwayBillsRoute
  ExpensesRoute: typeof ExpensesRoute
  FeaturesRoute: typeof FeaturesRoute
  GoodsReceiptNotesRoute: typeof GoodsReceiptNotesRoute
  GstRoute: typeof GstRoute
  Gstr2bRoute: typeof Gstr2bRoute
  InvoicesRoute: typeof InvoicesRoute
  ItcRoute: typeof ItcRoute
  ItemsRoute: typeof ItemsRoute
  JournalEntriesRoute: typeof JournalEntriesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PartiesRoute: typeof PartiesRoute
  PartnersRoute: typeof PartnersRoute
  PaymentsRoute: typeof PaymentsRoute
  PhysicalStockRoute: typeof PhysicalStockRoute
  PosRoute: typeof PosRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProformaInvoicesRoute: typeof ProformaInvoicesRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  QuotationsRoute: typeof QuotationsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  SalesReturnsRoute: typeof SalesReturnsRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  StockAdjustmentsRoute: typeof StockAdjustmentsRoute
  StockTransfersRoute: typeof StockTransfersRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  TermsRoute: typeof TermsRoute
  WarehousesRoute: typeof WarehousesRoute
  WidgetsRoute: typeof WidgetsRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthPlanSelectionRoute: typeof AuthPlanSelectionRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  BusinessCreateRoute: typeof BusinessCreateRoute
  ITokenRoute: typeof ITokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-orders': {
      id: '/store-orders'
      path: '/store-orders'
      fullPath: '/store-orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-transfers': {
      id: '/stock-transfers'
      path: '/stock-transfers'
      fullPath: '/stock-transfers'
      preLoaderRoute: typeof StockTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-adjustments': {
      id: '/stock-adjustments'
      path: '/stock-adjustments'
      fullPath: '/stock-adjustments'
      preLoaderRoute: typeof StockAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-returns': {
      id: '/sales-returns'
      path: '/sales-returns'
      fullPath: '/sales-returns'
      preLoaderRoute: typeof SalesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma-invoices': {
      id: '/proforma-invoices'
      path: '/proforma-invoices'
      fullPath: '/proforma-invoices'
      preLoaderRoute: typeof ProformaInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-stock': {
      id: '/physical-stock'
      path: '/physical-stock'
      fullPath: '/physical-stock'
      preLoaderRoute: typeof PhysicalStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-entries': {
      id: '/journal-entries'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof JournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itc': {
      id: '/itc'
      path: '/itc'
      fullPath: '/itc'
      preLoaderRoute: typeof ItcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gstr2b': {
      id: '/gstr2b'
      path: '/gstr2b'
      fullPath: '/gstr2b'
      preLoaderRoute: typeof Gstr2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods-receipt-notes': {
      id: '/goods-receipt-notes'
      path: '/goods-receipt-notes'
      fullPath: '/goods-receipt-notes'
      preLoaderRoute: typeof GoodsReceiptNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eway-bills': {
      id: '/eway-bills'
      path: '/eway-bills'
      fullPath: '/eway-bills'
      preLoaderRoute: typeof EwayBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-invoicing': {
      id: '/e-invoicing'
      path: '/e-invoicing'
      fullPath: '/e-invoicing'
      preLoaderRoute: typeof EInvoicingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans': {
      id: '/delivery-challans'
      path: '/delivery-challans'
      fullPath: '/delivery-challans'
      preLoaderRoute: typeof DeliveryChallansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-notes': {
      id: '/credit-notes'
      path: '/credit-notes'
      fullPath: '/credit-notes'
      preLoaderRoute: typeof CreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-and-bank': {
      id: '/cash-and-bank'
      path: '/cash-and-bank'
      fullPath: '/cash-and-bank'
      preLoaderRoute: typeof CashAndBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-reconciliation': {
      id: '/bank-reconciliation'
      path: '/bank-reconciliation'
      fullPath: '/bank-reconciliation'
      preLoaderRoute: typeof BankReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automated-invoices': {
      id: '/automated-invoices'
      path: '/automated-invoices'
      fullPath: '/automated-invoices'
      preLoaderRoute: typeof AutomatedInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/create': {
      id: '/business/create'
      path: '/business/create'
      fullPath: '/business/create'
      preLoaderRoute: typeof BusinessCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/plan-selection': {
      id: '/auth/plan-selection'
      path: '/auth/plan-selection'
      fullPath: '/auth/plan-selection'
      preLoaderRoute: typeof AuthPlanSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutomatedInvoicesRoute: AutomatedInvoicesRoute,
  BankReconciliationRoute: BankReconciliationRoute,
  CashAndBankRoute: CashAndBankRoute,
  ContactRoute: ContactRoute,
  CreditNotesRoute: CreditNotesRoute,
  DeliveryChallansRoute: DeliveryChallansRoute,
  EInvoicingRoute: EInvoicingRoute,
  EwayBillsRoute: EwayBillsRoute,
  ExpensesRoute: ExpensesRoute,
  FeaturesRoute: FeaturesRoute,
  GoodsReceiptNotesRoute: GoodsReceiptNotesRoute,
  GstRoute: GstRoute,
  Gstr2bRoute: Gstr2bRoute,
  InvoicesRoute: InvoicesRoute,
  ItcRoute: ItcRoute,
  ItemsRoute: ItemsRoute,
  JournalEntriesRoute: JournalEntriesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PartiesRoute: PartiesRoute,
  PartnersRoute: PartnersRoute,
  PaymentsRoute: PaymentsRoute,
  PhysicalStockRoute: PhysicalStockRoute,
  PosRoute: PosRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProformaInvoicesRoute: ProformaInvoicesRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  QuotationsRoute: QuotationsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  SalesReturnsRoute: SalesReturnsRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  StockAdjustmentsRoute: StockAdjustmentsRoute,
  StockTransfersRoute: StockTransfersRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  TermsRoute: TermsRoute,
  WarehousesRoute: WarehousesRoute,
  WidgetsRoute: WidgetsRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthPlanSelectionRoute: AuthPlanSelectionRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  BusinessCreateRoute: BusinessCreateRoute,
  ITokenRoute: ITokenRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
