/**
 * The read-only gate's allowlist, checked against the real router (no
 * database needed: it only enumerates procedure definitions).
 *
 *  - typo guard: every READ_ONLY_EXEMPT / SUSPENDED_ALLOWED entry is a real
 *    procedure of the right kind;
 *  - review snapshot: the complete gated-vs-exempt split of every mutation is
 *    committed in __snapshots__/mutation-gate.md, so a new mutation shows up
 *    in the diff as "gated" (refused in read-only mode by default) and anyone
 *    who allowlists it has to do so deliberately.
 */

import { describe, it, expect } from "vitest";
import { listProcedures } from "./helpers/sweep-procs.js";
import { READ_ONLY_EXEMPT, SUSPENDED_ALLOWED } from "../lib/entitlement-exempt.js";

const procs = listProcedures();
const byPath = new Map(procs.map((p) => [p.path, p]));
const mutations = procs.filter((p) => p.type === "mutation");

describe("READ_ONLY_EXEMPT", () => {
  it("only names procedures that exist, and only mutations", () => {
    const missing = [...READ_ONLY_EXEMPT].filter((p) => !byPath.has(p));
    expect(missing).toEqual([]);
    const notMutations = [...READ_ONLY_EXEMPT].filter((p) => byPath.get(p)!.type !== "mutation");
    expect(notMutations).toEqual([]);
  });

  it("SUSPENDED_ALLOWED only names real queries on a gated (tenant-scoped) base", () => {
    for (const path of SUSPENDED_ALLOWED) {
      const p = byPath.get(path);
      expect(p, path).toBeDefined();
      expect(p!.type).toBe("query");
      expect(["tenant", "business", "authorized"]).toContain(p!.base);
    }
  });

  it("keeps every recovery path open: billing, auth, exports", () => {
    for (const path of ["billing.subscribePlan", "billing.changePlan", "billing.demoCheckout", "auth.logout", "business.exportData", "selfExport.request"]) {
      expect(READ_ONLY_EXEMPT.has(path), path).toBe(true);
    }
  });
});

describe("mutation gate split", () => {
  it("is unchanged (review mutation-gate.md when a mutation is added)", async () => {
    const gatedBase = (b: string) => b === "tenant" || b === "business" || b === "authorized";
    const lines: string[] = [
      "# Mutation gate split (generated by entitlement-exempt.test.ts, review changes)",
      "",
      "gated = tenant-scoped base, refused in read-only mode; exempt = allowlisted in READ_ONLY_EXEMPT;",
      "ungated = built on a public/protected base, so the gate never runs.",
      "",
    ];
    const rows = mutations
      .map((m) => {
        const exempt = READ_ONLY_EXEMPT.has(m.path);
        const status = !gatedBase(m.base) ? "ungated" : exempt ? "exempt" : "gated";
        return { path: m.path, base: m.base, status };
      })
      .sort((a, b) => a.path.localeCompare(b.path));
    const count = (s: string) => rows.filter((r) => r.status === s).length;
    lines.push(`mutations: ${rows.length} (gated ${count("gated")}, exempt ${count("exempt")}, ungated ${count("ungated")})`, "");
    lines.push("| procedure | base | status |", "|---|---|---|");
    for (const r of rows) lines.push(`| ${r.path} | ${r.base} | ${r.status} |`);
    await expect(lines.join("\n") + "\n").toMatchFileSnapshot("./integration/__snapshots__/mutation-gate.md");
  });

  it("gates by default: every tenant-scoped mutation outside the allowlist is gated", () => {
    const open = mutations.filter((m) => ["tenant", "business", "authorized"].includes(m.base) && READ_ONLY_EXEMPT.has(m.path)).map((m) => m.path);
    // Only these tenant-scoped mutations may stay open in read-only mode.
    expect(open.sort()).toEqual([
      "business.exportData",
      "eInvoice.testConnection",
      "party.lookupGstin",
      "share.revoke",
      "tenant.removeMember",
      "tenant.revokeInvitation",
    ]);
  });
});
