/**
 * FEATURE_GATES checked against the real router (no database needed):
 *
 *  - typo guard: every procedure the registry names exists, and exempt entries
 *    are real mutations;
 *  - completeness: every mutation under a router in FEATURE_GATE_CHECKED_ROUTERS
 *    is gated by some flag or listed in FEATURE_GATE_EXEMPT with a reason, so a
 *    new mutation in a gated router fails here until someone decides;
 *  - a gated procedure sits on a tenant-scoped base (otherwise the middleware
 *    that enforces the flag never runs for it);
 *  - snapshot: __snapshots__/feature-gate.md lists procedure -> feature, so a
 *    change to the matrix shows up in review.
 */

import { describe, it, expect } from "vitest";
import {
  FEATURE_GATES,
  FEATURE_GATE_CHECKED_ROUTERS,
  FEATURE_GATE_EXEMPT,
  PLAN_FLAG_KEYS,
  featureGatesFor,
  namedGateProcedures,
} from "@fintranzact/shared";
import { listProcedures } from "./helpers/sweep-procs.js";
import { writesBatchFields } from "../lib/feature-gate.js";

const procs = listProcedures();
const byPath = new Map(procs.map((p) => [p.path, p]));
const gatedBase = (b: string) => b === "tenant" || b === "business" || b === "authorized";

describe("FEATURE_GATES against the router", () => {
  it("only names procedures that exist", () => {
    expect(namedGateProcedures().filter((p) => !byPath.has(p))).toEqual([]);
    expect(Object.keys(FEATURE_GATE_EXEMPT).filter((p) => !byPath.has(p))).toEqual([]);
    for (const def of Object.values(FEATURE_GATES)) {
      for (const r of def.routers) expect(procs.some((p) => p.router === r), `router ${r}`).toBe(true);
    }
  });

  it("exempt entries are mutations, each with a reason, and none is also gated unconditionally by name", () => {
    for (const [path, reason] of Object.entries(FEATURE_GATE_EXEMPT)) {
      expect(byPath.get(path)!.type, path).toBe("mutation");
      expect(reason.length, path).toBeGreaterThan(10);
      expect(featureGatesFor(path, "mutation").filter((m) => !m.condition), path).toEqual([]);
    }
  });

  it("every mutation of a checked router is gated or explicitly exempt", () => {
    const uncovered = procs
      .filter((p) => p.type === "mutation" && FEATURE_GATE_CHECKED_ROUTERS.includes(p.router))
      .filter((p) => featureGatesFor(p.path, p.type).length === 0 && !FEATURE_GATE_EXEMPT[p.path])
      .map((p) => p.path);
    expect(uncovered, "add these to FEATURE_GATES (or FEATURE_GATE_EXEMPT with a reason) in packages/shared/src/feature-gates.ts").toEqual([]);
  });

  it("every gated procedure is on a tenant-scoped base, where the gate middleware runs", () => {
    const off = procs.filter((p) => featureGatesFor(p.path, p.type).length > 0 && !gatedBase(p.base)).map((p) => `${p.path} (${p.base})`);
    expect(off).toEqual([]);
  });

  it("every gated flag actually gates something", () => {
    for (const flag of PLAN_FLAG_KEYS) {
      if (FEATURE_GATES[flag].kind !== "gated") continue;
      expect(procs.some((p) => featureGatesFor(p.path, p.type).some((m) => m.flag === flag)), flag).toBe(true);
    }
  });
});

describe("feature gate matrix", () => {
  it("is unchanged (review feature-gate.md when a gated procedure is added)", async () => {
    const lines = [
      "# Plan feature gates (generated by feature-gate-registry.test.ts, review changes)",
      "",
      "procedure -> the plan flag that must be on. `always` = refused whenever the plan lacks the flag;",
      "a condition = refused only when the call is that kind of use (see lib/feature-gate.ts).",
      "Queries stay open except entry points listed here. Operational / not-built flags gate nothing.",
      "",
      "| flag | kind | feature |",
      "|---|---|---|",
      ...PLAN_FLAG_KEYS.map((f) => `| ${f} | ${FEATURE_GATES[f].kind} | ${FEATURE_GATES[f].name} |`),
      "",
      "| procedure | type | flag | when |",
      "|---|---|---|---|",
    ];
    const rows = procs
      .flatMap((p) => featureGatesFor(p.path, p.type).map((m) => ({ path: p.path, type: p.type, flag: m.flag, when: m.condition ?? "always" })))
      .sort((a, b) => a.flag.localeCompare(b.flag) || a.path.localeCompare(b.path));
    for (const r of rows) lines.push(`| ${r.path} | ${r.type} | ${r.flag} | ${r.when} |`);
    lines.push("", "Deliberately not gated (checked routers):", "", "| procedure | reason |", "|---|---|");
    for (const [path, reason] of Object.entries(FEATURE_GATE_EXEMPT).sort(([a], [b]) => a.localeCompare(b))) lines.push(`| ${path} | ${reason} |`);
    await expect(lines.join("\n") + "\n").toMatchFileSnapshot("./integration/__snapshots__/feature-gate.md");
  });
});

describe("writesBatchFields", () => {
  it.each([
    [{ lineItems: [{ itemId: "a", batchId: "b" }] }, true],
    [{ lines: [{ itemId: "a", newBatch: { batchNumber: "B1" } }] }, true],
    [{ openingBatch: { batchNumber: "B1", expiryDate: "2030-01-01" } }, true],
    [{ lineItems: [{ itemId: "a", batchId: null, batchNumber: "" }] }, false],
    [{ lineItems: [{ itemId: "a", quantity: "1" }] }, false],
    [null, false],
    ["text", false],
  ])("%j -> %s", (input, expected) => {
    expect(writesBatchFields(input)).toBe(expected);
  });
});
