/**
 * Route registry for the REST endpoints outside tRPC. Static scan of the
 * route registrations in server.ts and http/*.ts (server.ts boots a listener
 * and a database on import, so the Hono route table cannot be loaded in a
 * unit test) compared with REST_ENTITLEMENT_POLICY. A new route with no
 * policy row fails here; so does a stale row. The generated table is also
 * committed as integration/__snapshots__/rest-entitlement-policy.md for review.
 */

import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { REST_ENTITLEMENT_POLICY } from "../http/rest-entitlement-policy.js";

const SRC = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VERBS = "get|post|put|patch|delete|all|on|options|head";
const CALL = new RegExp(`\\bapp\\.(${VERBS})\\(`, "g");
const LITERAL = new RegExp(`\\bapp\\.(${VERBS})\\(\\s*(["'\`])([^"'\`]+)\\2`, "g");

const files = [
  "server.ts",
  ...readdirSync(path.join(SRC, "http"))
    .filter((f) => f.endsWith(".ts") && f !== "entitlement-guard.ts" && f !== "rest-entitlement-policy.ts")
    .map((f) => `http/${f}`),
];

interface Found { key: string; file: string }
const found: Found[] = [];
const calls: Record<string, number> = {};
for (const file of files) {
  const src = readFileSync(path.join(SRC, file), "utf8").replace(/^\s*(\/\*|\*|\/\/).*$/gm, "");
  calls[file] = [...src.matchAll(CALL)].length;
  for (const m of src.matchAll(LITERAL)) found.push({ key: `${m[1]!.toUpperCase()} ${m[3]}`, file });
  // The tRPC mount is registered with app.use.
  if (/app\.use\(\s*"\/api\/trpc\/\*",\s*async \(c\) =>/.test(src)) found.push({ key: "ALL /api/trpc/*", file });
}

describe("REST entitlement policy", () => {
  it("finds every route registration (none built from a variable)", () => {
    for (const file of files) {
      const literals = found.filter((f) => f.file === file && !f.key.startsWith("ALL /api/trpc")).length;
      expect(literals, `${file}: a route is registered with a non-literal path; use a string literal so it can be checked`).toBe(calls[file]);
    }
    expect(found.length).toBeGreaterThan(20);
  });

  it("has a policy for every registered route", () => {
    const missing = found.map((f) => f.key).filter((k) => !(k in REST_ENTITLEMENT_POLICY));
    expect(missing, "add these to REST_ENTITLEMENT_POLICY (http/rest-entitlement-policy.ts) with a deliberate decision").toEqual([]);
  });

  it("has no stale rows", () => {
    const keys = new Set(found.map((f) => f.key));
    expect(Object.keys(REST_ENTITLEMENT_POLICY).filter((k) => !keys.has(k))).toEqual([]);
  });

  it("registers each route once", () => {
    const keys = found.map((f) => f.key);
    expect(keys.filter((k, i) => keys.indexOf(k) !== i)).toEqual([]);
  });

  it("write-gated and import routes call refuseIfReadOnly in their own file", () => {
    for (const f of found) {
      const policy = REST_ENTITLEMENT_POLICY[f.key];
      const isWrite = policy === "write-gated" || f.key === "POST /api/selfImport/:tenantId";
      if (!isWrite) continue;
      const src = readFileSync(path.join(SRC, f.file), "utf8");
      expect(src, f.key).toMatch(/refuseIfReadOnly|requireWritableRest/);
    }
  });

  it("session-authenticated non-GET routes are write-gated or a deliberate exemption", () => {
    // Anything else that mutates over REST must be one of these; a plain "read" POST is a mistake.
    for (const [key, policy] of Object.entries(REST_ENTITLEMENT_POLICY)) {
      if (key.startsWith("GET ")) continue;
      expect(["write-gated", "exempt-download", "exempt-webhook", "exempt-auth", "signed-token", "public-neutral", "trpc-gated"], key).toContain(policy);
    }
  });

  it("matches the committed review table", async () => {
    const lines = [
      "# REST entitlement policy (generated by rest-entitlement-policy.test.ts, review changes)",
      "",
      "Every route outside tRPC and what a read-only or suspended organisation may do. See docs/ENTITLEMENTS.md.",
      "",
      "| route | policy | file |",
      "|---|---|---|",
      ...found
        .slice()
        .sort((a, b) => a.key.localeCompare(b.key))
        .map((f) => `| ${f.key} | ${REST_ENTITLEMENT_POLICY[f.key]} | ${f.file} |`),
    ];
    await expect(lines.join("\n") + "\n").toMatchFileSnapshot("./integration/__snapshots__/rest-entitlement-policy.md");
  });
});
