/**
 * Printable e-way bill in the standard EWB-01 layout: the e-way bill number,
 * date, generator and validity with a QR, Part A (supplier, recipient,
 * places of dispatch and delivery, document, value, HSN, reason,
 * transporter) and Part B (mode, vehicle, from, entered date / by), one row
 * per vehicle update.
 */
import PDFDocument from "pdfkit";
import { Ctx, drawTable, image, line, rect, registerFonts, text, textHeight, type Column, type Doc, type Row } from "./invoice-templates/engine.js";
import { date, dateTime, inr, transportModeName } from "./invoice-templates/model.js";

export interface EwayBillPDFData {
  ewbNumber: string;
  ewbDate?: string;
  validUpto?: string;
  status: string;
  cancelReason?: string;
  generatedBy: { gstin: string; name: string };
  supplier: { gstin: string; name: string; address: string; state?: string };
  recipient: { gstin: string; name: string; address: string; state?: string };
  dispatchFrom: string;
  deliverTo: string;
  documentType: string;
  documentNumber: string;
  documentDate: string;
  transactionType: string;
  /** Rupees. */
  valueOfGoods: string;
  taxableValue: string;
  cgst?: string;
  sgst?: string;
  igst?: string;
  hsnCodes: string[];
  reason: string;
  transporterId?: string;
  transporterName?: string;
  distance?: number;
  /** Part B rows, latest first. */
  partB: Array<{ mode?: string; vehicle: string; from?: string; enteredDate?: string; enteredBy?: string }>;
  qrDataUrl?: string;
  isPaidPlan?: boolean;
}

const W = 595.28;
const H = 841.89;
const M = 36;
const CW = W - 2 * M;
const LBL = "#555555";

function group(n: string): string {
  return n.replace(/\s+/g, "").replace(/(\d{4})(?=\d)/g, "$1 ");
}

function kvRows(doc: Doc, rows: Array<[string, string]>, x: number, y: number, w: number, labelW: number): number {
  for (const [k, v] of rows) {
    const h = Math.max(
      textHeight(doc, k, { w: labelW - 6, size: 8 }),
      textHeight(doc, v || "—", { w: w - labelW, size: 8, bold: true }),
    );
    text(doc, k, x, y, { w: labelW - 6, size: 8, color: LBL });
    text(doc, v || "—", x + labelW, y, { w: w - labelW, size: 8, bold: true });
    y += h + 3.5;
  }
  return y;
}

function sectionTitle(doc: Doc, s: string, y: number): number {
  rect(doc, M, y, CW, 16, { fill: "#eef1f5" });
  text(doc, s, M + 6, y + 3.5, { w: CW - 12, size: 8.5, bold: true });
  return y + 22;
}

export function generateEwayBillPDF(d: EwayBillPDFData): Doc {
  const doc = new PDFDocument({
    size: [W, H],
    margin: 0,
    bufferPages: true,
    info: { Title: `e-Way Bill ${d.ewbNumber}`, Author: d.generatedBy.name, Creator: "Fintranzact" },
  });
  registerFonts(doc);
  let y = M;

  // ── Title and header block ───────────────────────────────
  y += text(doc, "e-Way Bill", M, y, { w: CW, size: 16, bold: true, align: "center" }) + 10;
  const qr = 92;
  const hasQr = image(doc, d.qrDataUrl, M + CW - qr, y, qr, qr);
  const headW = CW - (hasQr ? qr + 16 : 0);
  const headRows: Array<[string, string]> = [
    ["E-Way Bill No.", group(d.ewbNumber)],
    ["E-Way Bill Date", dateTime(d.ewbDate)],
    ["Generated By", `${d.generatedBy.gstin} - ${d.generatedBy.name}`],
    ["Valid From", `${dateTime(d.ewbDate)}${d.distance ? ` [${d.distance} Kms]` : ""}`],
    ["Valid Until", dateTime(d.validUpto)],
  ];
  if (d.status === "cancelled") headRows.push(["Status", `CANCELLED${d.cancelReason ? ` (${d.cancelReason})` : ""}`]);
  y = Math.max(kvRows(doc, headRows, M, y, headW, 120), hasQr ? y + qr : y) + 10;

  // ── Part A ───────────────────────────────────────────────
  y = sectionTitle(doc, "Part - A", y);
  const taxes = [
    d.cgst && parseFloat(d.cgst) ? `CGST ${inr(Math.round(parseFloat(d.cgst) * 100))}` : "",
    d.sgst && parseFloat(d.sgst) ? `SGST ${inr(Math.round(parseFloat(d.sgst) * 100))}` : "",
    d.igst && parseFloat(d.igst) ? `IGST ${inr(Math.round(parseFloat(d.igst) * 100))}` : "",
  ].filter(Boolean).join(" · ");
  const partA: Array<[string, string]> = [
    ["GSTIN of Supplier", `${d.supplier.gstin || "URP"} - ${d.supplier.name}`],
    ["Place of Dispatch", d.dispatchFrom],
    ["GSTIN of Recipient", `${d.recipient.gstin || "URP"} - ${d.recipient.name}`],
    ["Place of Delivery", d.deliverTo],
    ["Document No.", d.documentNumber],
    ["Document Date", date(d.documentDate)],
    ["Transaction Type", d.transactionType],
    ["Value of Goods", `₹${inr(Math.round(parseFloat(d.valueOfGoods || "0") * 100))}${taxes ? ` (Taxable ₹${inr(Math.round(parseFloat(d.taxableValue || "0") * 100))} · ${taxes})` : ""}`],
    ["HSN Code", d.hsnCodes.filter(Boolean).join(", ")],
    ["Reason for Transportation", d.reason],
    ["Transporter", [d.transporterId, d.transporterName].filter(Boolean).join(" - ")],
  ];
  y = kvRows(doc, partA, M + 6, y, CW - 12, 140) + 8;

  // ── Part B ───────────────────────────────────────────────
  y = sectionTitle(doc, "Part - B", y);
  const cols: Column[] = [
    { header: "Mode", w: 50 },
    { header: "Vehicle / Trans Doc No. & Dt.", w: 0, flex: 1.4 },
    { header: "From", w: 0, flex: 1 },
    { header: "Entered Date", w: 92 },
    { header: "Entered By", w: 0, flex: 1.2 },
    { header: "CEWB No. (If any)", w: 70 },
  ];
  const rows: Row[] = (d.partB.length ? d.partB : [{ vehicle: "" }]).map((p) => ({
    cells: [transportModeName(p.mode) || "—", p.vehicle || "—", p.from || "—", dateTime(p.enteredDate) || "—", p.enteredBy || "—", "—"],
  }));
  const ctx = new Ctx(doc, undefined as never, { size: [W, H], margins: { t: M, r: M, b: M, l: M } });
  y = drawTable(ctx, y, {
    columns: cols,
    rows,
    style: { size: 7.8, padX: 4, padY: 3.5, grid: { w: 0.5, c: "#9aa3ae" }, headerFill: "#f5f7fa", headerBold: true },
    newPage: (c) => { c.addPage(); return M; },
  });

  // ── Footer ───────────────────────────────────────────────
  y += 14;
  line(doc, M, y, M + CW, y, "#cccccc", 0.5);
  text(doc, "Printed from Fintranzact. Verify this e-way bill on ewaybillgst.gov.in with the EWB number above.", M, y + 5, { w: CW, size: 6.8, color: "#777777", align: "center" });
  if (!d.isPaidPlan) text(doc, "Powered by Fintranzact", 0, H - 14, { w: W, size: 5.5, color: "#a0a0a8", align: "center" });

  if (d.status === "cancelled") {
    doc.save();
    doc.translate(W / 2, H / 2).rotate(-30);
    doc.font("NotoSans-Bold").fontSize(64).fillColor("#cc2222").fillOpacity(0.1);
    const w = doc.widthOfString("CANCELLED");
    doc.text("CANCELLED", -w / 2, -40, { lineBreak: false });
    doc.restore();
  }
  return doc;
}
