/**
 * SQL fragments shared by the audit rules. Each one mirrors a calculation the
 * API does in TypeScript, so a rule can recompute what the writer should have
 * stored. Keep them in step with the code they cite.
 */

import type { AuditRule, Severity } from "./types.js";

/** Build a rule. `name` becomes the part after the table in the rule id. */
export function rule(
  table: string,
  name: string,
  severity: Severity,
  description: string,
  writers: string[],
  sql: string,
): AuditRule {
  return { id: `${table}.${name}`, table, severity, description, writers, sql };
}

/** Rupee tolerance for comparing stored money with a recomputed value. */
export const MONEY_TOLERANCE = "0.011";
/** Tolerance for base-unit stock quantities (numeric(15,3)). */
export const QTY_TOLERANCE = "0.0005";

/**
 * Which way a document moves stock: -1 out, +1 in, 0 not at all.
 * Mirrors documentStockDirection() in lib/inventory-service.ts.
 */
export function stockDirection(alias: string): string {
  return `(CASE
    WHEN ${alias}.document_type IN ('invoice', 'delivery_challan') THEN CASE WHEN ${alias}.type = 'sale' THEN -1 ELSE 1 END
    WHEN ${alias}.document_type = 'purchase_return' THEN -1
    WHEN ${alias}.document_type IN ('sales_return', 'goods_receipt_note') THEN 1
    ELSE 0 END)`;
}

/** Line value before discount: money.mul(unitPrice, quantity). */
export function lineGross(li: string): string {
  return `ROUND(${li}.unit_price::numeric * ${li}.quantity::numeric, 2)`;
}

/**
 * Taxable value of a line after its discount — calcLineItem().afterDiscount
 * in @fintranzact/shared calc.ts (tax-exclusive, which is how every writer
 * stores lines).
 */
export function lineTaxable(li: string): string {
  return `(${lineGross(li)} - ROUND(${lineGross(li)} * ${li}.discount_percent::numeric / 100, 2))`;
}

/** 2-digit GST state code of a party/business row: saved code, else GSTIN prefix (gstStateCode). */
export function gstStateCodeSql(alias: string): string {
  return `COALESCE(NULLIF(trim(${alias}.state_code), ''), CASE WHEN LEFT(${alias}.gstin, 2) ~ '^[0-9]{2}$' THEN LEFT(${alias}.gstin, 2) END)`;
}

/**
 * Whether a supply between seller and buyer rows is intra-state — mirrors
 * isIntraStateSupply in @fintranzact/shared gst.ts: state codes (or GSTIN
 * prefixes) when both have one, else state names, else (buyer's state
 * unknown) intra-state at the supplier's location.
 */
export function intraStateSql(seller: string, buyer: string): string {
  const sc = gstStateCodeSql(seller);
  const bc = gstStateCodeSql(buyer);
  return `(CASE WHEN ${sc} IS NOT NULL AND ${bc} IS NOT NULL THEN ${sc} = ${bc}
     WHEN NULLIF(trim(${seller}.state), '') IS NOT NULL AND NULLIF(trim(${buyer}.state), '') IS NOT NULL
       THEN lower(trim(${seller}.state)) = lower(trim(${buyer}.state))
     ELSE TRUE END)`;
}

/** Rates a GST invoice line can legitimately carry (%). Anything else is a typo. */
export const GST_RATES = "(0, 0.1, 0.25, 1, 1.5, 3, 5, 6, 7.5, 12, 18, 28, 40)";

/** GSTIN shape (validators.ts GSTIN_REGEX). */
export const GSTIN_PATTERN = "'^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'";

/**
 * True when a document was typed in by a person through the app (the invoice
 * form, POS or a conversion) rather than generated by a background job or an
 * import. Only those rows are expected to carry an audit_log entry and a
 * creating user.
 */
export function userEntered(alias: string): string {
  return `(${alias}.source IS NULL OR ${alias}.source = 'pos')`;
}
